### PR TITLE
Update ee builder to generate controller config

### PR DESCRIPTION
**Pull request by sean-m-sullivan**
# What does this PR do?
Update EE builder to generate controller configuration so it can more easily push updated Ee's to a registery. The user is free to then override this or ignore it.

Updated readme's and worked to make the definition of images more definite, clear, and working.

# How should this be tested?

Automated tests but this has been tested.

# Is there a relevant Issue open for this?
#33

### CODE REVIEW

**Comment by sean-m-sullivan** [comment]
@anshulbehl love to get your input on changes

**Review by Tompage1994 — CHANGES_REQUESTED** [review]
Mostly looks good. Could you add to the readme the vars which are set `controller_execution_environments` and perhaps how to make use of them (i.e. an example playbook which creates the EE and sets it in controller)?

**Comment by sean-m-sullivan** [comment]
@Tompage1994 I am working on a Blog post and entire Repo to do exactly that, I figured we would add links in the Readme once I get it done. That is what prompted this.

**Comment by Tompage1994** [comment]
@sean-m-sullivan  Ok, based on that I'll accept this and I've raised #35 and assigned to you to add when you're ready.

**Pull request merged**
